### ISSUE TITLE
estimate_dimensionality_cv not in latest pypi version.

### ISSUE THREAD

**Issue by Vivdaddy** [cblearn/cblearn#70]
Hi,

The current cblearn version (0.1.2) from pypi does not seem to contain embedding.estimate_dimensionality_cv. Does the next release plan to? Or is this a bug?

I got it to work by copying the files over from the github repo, but it would be nice for it to work right off the bat.

![bad_import](https://github.com/cblearn/cblearn/assets/37226693/18aba504-d6d7-4603-8026-7809ce8822b2)

**Comment by dekuenstle** [comment]
You are right, this function was implemented after the release of `0.1.2`. In a few minutes (once all tests passed), I will release `0.2.0` which should include this function besides many improvements in the documentation and updated dependencies.

I think it was confusing, that the documentation by default showed "latest" (=the main branch) instead of "stable" (=the latest release on pipy). This should be fixed now, too. Sorry for the inconvenience.
